### ISSUE TITLE
Can't fetch JWT token

### ISSUE THREAD

**Issue by grzegor** [0xdevalias/poc-beeper-password-reset#2] opened 2023-09-14 07:17 UTC
Can't get it to work, it can't fetch the token.
```
% ./beeper-password-reset.ts login-email --email $MY_EMAIL
✔ Enter the challenge code sent to your email: … $EMAIL_CODE_I_GOT

Your JWT Token:  undefined
```

I don't really know what I'm doing but I skimmed at your code, and tried issuing each reqest with cli curl. It got me the email with one time code just fine but then after 
```
% curl -X POST https://api.beeper.com/user/login/response -H "Authorization: Bearer BEEPER-PRIVATE-API-PLEASE-DONT-USE" -H "Content-Type: application/json" -d '{"request":"REDACTED_REQUEST","response":"EMAIL_CODE_I_GOT"}'
```
I get `{"waitlist":REDACTED_NUMBER}` as a response, the number is random with 5 digits and I feel like this is unexpected flow

**Comment by 0xdevalias** [comment] 2023-09-14 07:21
Do you have a current/active beeper account, or are you on the wait list still? The response makes me think the latter.

I haven't personally tried the flow in a while, so it's possible something changed since I implemented it; but that's definitely not a response I ever experienced at the time.

**Comment by grzegor** [comment] 2023-09-14 07:22
I have a working account, I've been actively using it for 3 months

**Comment by grzegor** [comment] 2023-09-14 07:30
Ok, it magically started working now with the same commands it failed 10 minutes ago, probably a server side bug.

**Comment by 0xdevalias** [comment] 2023-09-15 00:29
True true. Glad it's working for you now!

I'll close this for now, but if it breaks again and you're able to reproduce it, feel free to open this thread again.

**Closed as not planned by 0xdevalias** 2023-09-15 00:29 UTC
